### ISSUE TITLE
Failing for Amazon Elasticsearch 6.3

### ISSUE THREAD

**Issue by ivkos** [VanRoy/spring-data-jest#100]
The library fails when the following conditions are met:

**Versions:**
* **Amazon Elasticsearch 6.3**
* spring-boot-starter-data-jest - **3.1.5.RELEASE**
* spring-boot-starter-parent - **2.0.5.RELEASE**
* aws-signing-request-interceptor - **0.0.22**
* org.elasticsearch:elasticsearch - **5.6.13**

```java
@Document(indexName = "some_entities", type = "some_entity")
@Setting(settingPath = "/elasticsearch/analyzers.json")
public class SomeEntity
{
    @Field(type = Keyword)
    private Integer id;

    ...
}
```

```
com.github.vanroy.springdata.jest.exception.JestElasticsearchException: Cannot execute jest action , response code : 400 , error : {"root_cause":[{"type":"illegal_argument_exception","reason":"Could not convert [id.index] to boolean"}],"type":"illegal_argument_exception","reason":"Could not convert [id.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [not_analyzed] as only [true] or [false] are allowed."}} , message : null
	at com.github.vanroy.springdata.jest.mapper.DefaultErrorMapper.mapError(DefaultErrorMapper.java:30)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.execute(JestElasticsearchTemplate.java:1218)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.executeWithAcknowledge(JestElasticsearchTemplate.java:1228)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.putMapping(JestElasticsearchTemplate.java:261)
	... 98 more
```

The only workaround I've found so far is using an older Amazon Elasticsearch cluster version (i.e. 5.6).

**Comment by VanRoy** [comment]
Hi  @ivkos . The new version if 3.2.0.RELEASE released tonight is now compatible with ES 6.x.
Please feel free to feedback if you detect some issues.
Thanks.
