### ISSUE TITLE
Cannot execute jest action , response code : 405

### ISSUE THREAD

**Issue by qracle** [VanRoy/spring-data-jest#118]
2019-07-16 03:32:13.086 ERROR[http-nio-9876-exec-5]c.g.vanroy.springdata.jest.mapper.DefaultErrorMapper.mapError:29 -Cannot execute jest action , response code : 405 , error : "Incorrect HTTP method for uri [/dc_wide_refund/wide_refund] and method [GET], allowed: [POST]" , message : null
2019-07-16 03:32:13.093 ERROR[http-nio-9876-exec-5]c.s.data.core.client.support.GlobalExceptionHandler.exception:22 -Cannot execute jest action , response code : 405 , error : "Incorrect HTTP method for uri [/dc_wide_refund/wide_refund] and method [GET], allowed: [POST]" , message : null
com.github.vanroy.springdata.jest.exception.JestElasticsearchException: Cannot execute jest action , response code : 405 , error : "Incorrect HTTP method for uri [/dc_wide_refund/wide_refund] and method [GET], allowed: [POST]" , message : null
        at com.github.vanroy.springdata.jest.mapper.DefaultErrorMapper.mapError(DefaultErrorMapper.java:30)
        at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.execute(JestElasticsearchTemplate.java:1119)
        at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.queryForObject(JestElasticsearchTemplate.java:377)
        at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.queryForObject(JestElasticsearchTemplate.java:362)
        at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.queryForObject(JestElasticsearchTemplate.java:353)
        at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.findById(AbstractElasticsearchRepository.java:111)
        at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.findById(AbstractElasticsearchRepository.java:60)
        at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)..............

====================================================================
**I'm using Aws Elasticsearch Service
I tried to trace the error link，plz see below
Why can't I use Get method?
** 
![image](https://user-images.githubusercontent.com/32318904/61264276-89db8280-a7be-11e9-83e5-bccda71c5912.png)

![image](https://user-images.githubusercontent.com/32318904/61264143-10439480-a7be-11e9-8f76-3671d56b67f2.png)

![image](https://user-images.githubusercontent.com/32318904/61264159-218ca100-a7be-11e9-9043-2dab038341fe.png)

![image](https://user-images.githubusercontent.com/32318904/61264190-349f7100-a7be-11e9-8138-704b6bb07fc1.png)

**Comment by VanRoy** [comment]
Hi @qracle , can you send me the versions of :

- SpringBoot
- SpringDataJest
- ES in your AWS account

**Comment by Jiezhi** [comment]
I'v got the issue those days, I debugged the code and found the code build a request like `HEAD http://192.168.x.x:9200//goods`  and the jest got the `405` response. 

It seems ES don't allow double slash in the request.And I removed the slash after es url in configuration file, and the issue disappeared.

**Comment by VanRoy** [comment]
Thanks @Jiezhi for your input.
@qracle Can you validate that it's fix your issue too ?

**Comment by qracle** [comment]
Yes,i fixed it.
But I'm so sorry for my late response. 
Thank you for your help!
