### ISSUE TITLE
ddl create mode not working with custom mappings and settings file

### ISSUE THREAD

**Issue by nitinsmartsense** [VanRoy/spring-data-jest#126]
Hello, 
Previously I was using TCL client to connect with elasticsearch, As per other doc TCP client will be deprecated in the next few releases
After I adding a dependency of spring-data-jest, I am not able to start my application in ddl create mode
Entity File:

````
@Document(indexName = "myindex", type = "myindex")
@Setting(settingPath = "/schema/country/settings.json")
@Mapping(mappingPath = "/schema/country/mappings.json")
public class MyIndex {
    private static final long serialVersionUID = 5793577025779020433L;

    @Id
    private String id;

  //.......other params
}
```
settings.json 

```
{
  "index": {
    "max_result_window": 10000000
  },
  "analysis": {
    "analyzer": {
      "custom_analyzer": {
        "type": "custom",
        "tokenizer": "whitespace",
        "filter": [
          "standard",
          "lowercase",
          "stop",
          "asciifolding"
        ],
        "char_filter": [
          "html_strip"
        ]
      }
    }
  }
}
```

mappings.json:
```
{
  "myindex": {
    "properties": {
      "id": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      }
      //other data
  }
}
```

Error logs:

```
Caused by: com.github.vanroy.springdata.jest.exception.JestElasticsearchException: Cannot execute jest action , response code : 400 , error : {"root_cause":[{"type":"parse_exception","reason":"unknown key [analysis] for create index"}],"type":"parse_exception","reason":"unknown key [analysis] for create index"} , message : null
  at com.github.vanroy.springdata.jest.mapper.DefaultErrorMapper.mapError(DefaultErrorMapper.java:30)
  at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.execute(JestElasticsearchTemplate.java:1126)
  at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.executeWithAcknowledge(JestElasticsearchTemplate.java:1136)
  at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndex(JestElasticsearchTemplate.java:197)
  at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndexWithSettings(JestElasticsearchTemplate.java:1339)
  at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndexIfNotCreated(JestElasticsearchTemplate.java:1330)
  at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndex(JestElasticsearchTemplate.java:178)
  at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.createIndex(AbstractElasticsearchRepository.java:96)
  at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.<init>(AbstractElasticsearchRepository.java:87)
  at org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository.<init>(SimpleElasticsearchRepository.java:36)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
  at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
  ... 57 common frames omitted

```

**Comment by VanRoy** [comment]
Hi @nitinsmartsense , I believe that the format of settings.json look like this.
The "analysis" node is in "index" node. Can you try this ? 

Thanks.
Julien.

```
{
    "index": {
        "number_of_shards": "1",
        "number_of_replicas": "0",
        "analysis": {
            "analyzer": {
                "emailAnalyzer": {
                    "type": "custom",
                    "tokenizer": "uax_url_email"
                }
            }
        }
    }
}
```

**Comment by VanRoy** [comment]
@nitinsmartsense Can you provide us an update for this issue ?

**Comment by nitinsmartsense** [comment]
Hey, @VanRoy 
Did not check it, we moved to new version of spring-data-elasticsearch

**Comment by VanRoy** [comment]
@nitinsmartsense Thanks for your reply.
