### ISSUE TITLE
java.lang.NoSuchMethodError in release 2.2.0.RELEASE

### ISSUE THREAD

**Issue by mihab** [VanRoy/spring-data-jest#19]
I get the following error when trying to perform a search query:

```
java.lang.NoSuchMethodError: io.searchbox.core.SearchResult$Hit.<init>(Lio/searchbox/core/SearchResult;Ljava/lang/Class;Lcom/google/gson/JsonElement;Ljava/lang/Class;Lcom/google/gson/JsonElement;Ljava/util/Map;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Double;)V
	at com.github.vanroy.springdata.jest.internal.ExtendedSearchResult.extractHit(ExtendedSearchResult.java:75) ~[spring-data-jest-2.2.0.RELEASE.jar:na]
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:86) ~[jest-common-2.0.3.jar:na]
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:67) ~[jest-common-2.0.3.jar:na]
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:63) ~[jest-common-2.0.3.jar:na]
	at com.github.vanroy.springdata.jest.mapper.DefaultJestResultsMapper.mapResults(DefaultJestResultsMapper.java:114) ~[spring-data-jest-2.2.0.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.queryForPage(JestElasticsearchTemplate.java:426) ~[spring-data-jest-2.2.0.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.queryForPage(JestElasticsearchTemplate.java:416) ~[spring-data-jest-2.2.0.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.queryForPage(JestElasticsearchTemplate.java:133) ~[spring-data-jest-2.2.0.RELEASE.jar:na]
	at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.search(AbstractElasticsearchRepository.java:189) ~[spring-data-elasticsearch-2.0.3.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:503) ~[spring-data-commons-1.12.3.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:488) ~[spring-data-commons-1.12.3.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.12.3.RELEASE.jar:na]
```

First I thought there would be a library mismatch, but that does not make any sense since I only use the searchbox library as a dependency of your com.github.vanroy.springdata.jest project and nowhere else. I made sure there is no other version of the library on the classpath. It just looks like the constructor you are calling in the ExtendedSearchResult does not seem to exist.

Also note that downgrading to version 2.1.4.RELEASE fixes the problem and everything works ok. Not sure how this happened, maybe you were releasing against a SNAPSHOT version of jest?

**Comment by VanRoy** [comment]
Hi @mihab ,

The release 2.2.0 work only with Jest 2.0.4 .

Spring Boot before version 1.4.3 use Jest 2.0.3.
You have two solutions to use version 2.2.0 : 

- Upgrade your project to Spring Boot 1.4.3
or
- Overriding Jest version to 2.0.4 with jest.version properties ( Spring Boot version overriding explained here : http://docs.spring.io/platform/docs/current/reference/html/getting-started-overriding-versions.html )

Keep me in touch.
Julien.

**Comment by mihab** [comment]
Yea I upgraded Spring Boot to 1.4.3 and can confirm 2.2.0.RELEASE is working fine. Thanks a lot for explaining!
