### ISSUE TITLE
Bean method 'elasticsearchClient' not loaded because auto-configuration 'ElasticsearchAutoConfiguration' was excluded

### ISSUE THREAD

**Issue by javadev** [VanRoy/spring-data-jest#22]
```
2017-02-11T16:48:16.697363+00:00 app[web.1]: ***************************
2017-02-11T16:48:16.697364+00:00 app[web.1]: APPLICATION FAILED TO START
2017-02-11T16:48:16.697364+00:00 app[web.1]: ***************************
2017-02-11T16:48:16.697365+00:00 app[web.1]: 
2017-02-11T16:48:16.697366+00:00 app[web.1]: Description:
2017-02-11T16:48:16.697366+00:00 app[web.1]: 
2017-02-11T16:48:16.697367+00:00 app[web.1]: Parameter 0 of method elasticsearchTemplate in no.lavoapp.config.ElasticSearchConfiguration required a bean of type 'org.elasticsearch.client.Client' that could not be found.
2017-02-11T16:48:16.697369+00:00 app[web.1]: 	- Bean method 'elasticsearchClient' not loaded because auto-configuration 'ElasticsearchAutoConfiguration' was excluded
2017-02-11T16:48:16.697369+00:00 app[web.1]: 
2017-02-11T16:48:16.697370+00:00 app[web.1]: 
2017-02-11T16:48:16.697370+00:00 app[web.1]: Action:
2017-02-11T16:48:16.697371+00:00 app[web.1]: 
2017-02-11T16:48:16.697371+00:00 app[web.1]: Consider revisiting the conditions above or defining a bean of type 'org.elasticsearch.client.Client' in your configuration.
```

**Comment by VanRoy** [comment]
Hi @javadev , could you send me more details to reproduct this issue please ?

**Comment by javadev** [comment]
I found a solution http://stackoverflow.com/questions/39623238/setting-up-bonsai-elasticsearch-in-jhipster-heroku/42206596#42206596

Valentyn

**Comment by umesh936** [comment]
I am facing the same problem. My config is
logging.level.org.springframework=INFO
cloud.aws.region.static=ap-south-1
data.elasticsearch.jest.uris=https://search-staging-lender-5-5-xxxxxxxxxxxxsm4xp5hmq.ap-south-1.es.amazonaws.com
data.elasticsearch.jest.read-timeout=10000
Exception I am getting
``

```

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticSearchConfiguration': Unsatisfied dependency expressed through field 'client'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.elasticsearch.client.Client' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:587)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:373)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1344)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
	... 6 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.elasticsearch.client.Client' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1509)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584)
```

```

**Comment by umesh936** [comment]
Can you guide me what I am missing here. I checked above url of stackoverflow.. not able to  figure out
 any solution

**Comment by uuhnaut69** [comment]
> ```
> 2017-02-11T16:48:16.697363+00:00 app[web.1]: ***************************
> 2017-02-11T16:48:16.697364+00:00 app[web.1]: APPLICATION FAILED TO START
> 2017-02-11T16:48:16.697364+00:00 app[web.1]: ***************************
> 2017-02-11T16:48:16.697365+00:00 app[web.1]: 
> 2017-02-11T16:48:16.697366+00:00 app[web.1]: Description:
> 2017-02-11T16:48:16.697366+00:00 app[web.1]: 
> 2017-02-11T16:48:16.697367+00:00 app[web.1]: Parameter 0 of method elasticsearchTemplate in no.lavoapp.config.ElasticSearchConfiguration required a bean of type 'org.elasticsearch.client.Client' that could not be found.
> 2017-02-11T16:48:16.697369+00:00 app[web.1]: 	- Bean method 'elasticsearchClient' not loaded because auto-configuration 'ElasticsearchAutoConfiguration' was excluded
> 2017-02-11T16:48:16.697369+00:00 app[web.1]: 
> 2017-02-11T16:48:16.697370+00:00 app[web.1]: 
> 2017-02-11T16:48:16.697370+00:00 app[web.1]: Action:
> 2017-02-11T16:48:16.697371+00:00 app[web.1]: 
> 2017-02-11T16:48:16.697371+00:00 app[web.1]: Consider revisiting the conditions above or defining a bean of type 'org.elasticsearch.client.Client' in your configuration.
> ```

I have the same issue, @VanRoy can you give me any advices, please ?

**Comment by VanRoy** [comment]
Hi @uuhnaut69 , with SpringDataJest you don't have access to elasticsearch Client.
Do you have try the solution described here : http://stackoverflow.com/questions/39623238/setting-up-bonsai-elasticsearch-in-jhipster-heroku/42206596#42206596 ?

**Comment by jonno85** [comment]
I'm having the same issue on an application running locally and connecting to a local instance of elasticsearch.
The weird things is compiling the spring boot application and running the jar, it works fine. If I run the task spring-boot:run, the program does not find the dependency

`com.j.autoinvito.service.ElasticsearchIndexService required a bean of type 'com.github.vanroy.springdata.jest.JestElasticsearchTemplate' that could not be found.`

**Comment by VanRoy** [comment]
@jonno85 Indeed it's weird. Can you send me the full stacktrace ?

**Comment by jonno85** [comment]
@VanRoy, after further tries, I realise that it is more an issue with the spring boot Bean initialisation. In the `@Service` class constructor, passing the `JestElasticsearchTemplate jestElasticsearchTemplate`, it does not injected properly and cause the error above with the following stacktrace:
`
2020-04-22 08:58:48.950 DEBUG 9149 --- [  restartedMain] reactor.netty.tcp.TcpResources           : [http] resources will use the default ConnectionProvider: reactor.netty.resources.PooledConnectionProvider@5a451b76
2020-04-22 08:58:49.038  WARN 9149 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticsearchIndexService' defined in file [.../target/classes/com/j/autoinvito/service/ElasticsearchIndexService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.vanroy.springdata.jest.JestElasticsearchTemplate' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2020-04-22 08:58:49.040  INFO 9149 --- [  restartedMain] c.h.h.HazelcastCacheRegionFactory        : Shutting down HazelcastCacheRegionFactory
2020-04-22 08:58:49.040  WARN 9149 --- [  restartedMain] c.h.h.i.IHazelcastInstanceFactory        : hibernate.cache.hazelcast.shutdown_on_session_factory_close property is set to 'false'. Leaving current HazelcastInstance active! (Warning: Do not disable Hazelcast hazelcast.shutdownhook.enabled property!)
2020-04-22 08:58:49.062  INFO 9149 --- [  restartedMain] com.hazelcast.core.LifecycleService      : [127.0.0.1]:18600 [dev] [3.12.6] [127.0.0.1]:18600 is SHUTTING_DOWN
2020-04-22 08:58:49.066  INFO 9149 --- [  restartedMain] com.hazelcast.instance.Node              : [127.0.0.1]:18600 [dev] [3.12.6] Shutting down connection manager...
2020-04-22 08:58:49.069  INFO 9149 --- [  restartedMain] com.hazelcast.instance.Node              : [127.0.0.1]:18600 [dev] [3.12.6] Shutting down node engine...
2020-04-22 08:58:49.074  INFO 9149 --- [  restartedMain] com.hazelcast.instance.NodeExtension     : [127.0.0.1]:18600 [dev] [3.12.6] Destroying node NodeExtension.
2020-04-22 08:58:49.075  INFO 9149 --- [  restartedMain] com.hazelcast.instance.Node              : [127.0.0.1]:18600 [dev] [3.12.6] Hazelcast Shutdown is completed in 11 ms.
2020-04-22 08:58:49.075  INFO 9149 --- [  restartedMain] com.hazelcast.core.LifecycleService      : [127.0.0.1]:18600 [dev] [3.12.6] [127.0.0.1]:18600 is SHUTDOWN
2020-04-22 08:58:49.075  INFO 9149 --- [  restartedMain] c.j.a.config.CacheConfiguration          : Closing Cache Manager
2020-04-22 08:58:49.077  INFO 9149 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
2020-04-22 08:58:52.083  INFO 9149 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Unregistering ...
2020-04-22 08:58:52.164  INFO 9149 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UAA/uaa:4eb5931a0c21060509cef4ef6128132c - deregister  status: 200
2020-04-22 08:58:52.173  INFO 9149 --- [  restartedMain] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
2020-04-22 08:58:52.435 ERROR 9149 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 2 of constructor in com.j.autoinvito.service.ElasticsearchIndexService required a bean of type 'com.github.vanroy.springdata.jest.JestElasticsearchTemplate' that could not be found.

Action:
Consider defining a bean of type 'com.github.vanroy.springdata.jest.JestElasticsearchTemplate' in your configuration.

Process finished with exit code 0
`

If instead I use the annotation `@Autowired` over the `JestElasticsearchTemplate` object, it does work. So it seems more a priority issue about the order of Spring boot Bean initialisation.

What do you think?
