### ISSUE TITLE
java.lang.NoSuchFieldError: LUCENE_4_0_0 error when using with Amazon ES 2.3.

### ISSUE THREAD

**Issue by ernsyn** [VanRoy/spring-data-jest#38]
Hi there,

Apologies if I'm posting this in the wrong place. 

I'm using spring-boot-starter-data-jest v2.3.1.RELEASE and had ES v2.3 running locally on my laptop. Everything works fine.

However, when trying it out on Amazon; also with ES v2.3, I get the following exception. 

2017-06-14 10:38:13.943  INFO 3246 --- [ost-startStop-1] com.dodeedo.ApplicationWebXml            : Starting ApplicationWebXml v0.0.1-SNAPSHOT on ip-172-31-11-244 with PID 3246 (/var/lib/tomcat8/webapps/ROOT/WEB-INF/classes started by tomcat in /usr/share/tomcat8)
2017-06-14 10:38:13.944  INFO 3246 --- [ost-startStop-1] com.dodeedo.ApplicationWebXml            : The following profiles are active: prod
2017-06-14 10:38:23.066  INFO 3246 --- [ost-startStop-1] com.dodeedo.config.WebConfigurer         : Web application configuration, using profiles: prod
2017-06-14 10:38:23.080  INFO 3246 --- [ost-startStop-1] com.dodeedo.config.WebConfigurer         : Web application fully configured
2017-06-14 10:38:23.513 DEBUG 3246 --- [ost-startStop-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Starting Liquibase synchronously
2017-06-14 10:38:25.855 DEBUG 3246 --- [ost-startStop-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase has updated your database in 2341 ms
2017-06-14 10:38:32.657  INFO 3246 --- [ost-startStop-1] a.d.j.ElasticsearchJestAutoConfiguration : Create test ES node
2017-06-14 10:38:32.785  WARN 3246 --- [ost-startStop-1] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService' defined in file [/var/lib/tomcat8/webapps/ROOT/WEB-INF/classes/com/dodeedo/service/UserService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userSearchRepository': Cannot resolve reference to bean 'elasticsearchTemplate' while setting bean property 'elasticsearchOperations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticsearchTemplate' defined in class path resource [com/dodeedo/config/ElasticsearchConfiguration.class]: Unsatisfied dependency expressed through method 'elasticsearchTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testClient' defined in class path resource [com/github/vanroy/springboot/autoconfigure/data/jest/ElasticsearchJestAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.searchbox.client.JestClient]: Factory method 'testClient' threw exception; nested exception is java.lang.NoSuchFieldError: LUCENE_4_0_0
2017-06-14 10:38:32.817  WARN 3246 --- [ost-startStop-1] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available)
2017-06-14 10:38:32.831 ERROR 3246 --- [ost-startStop-1] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService' defined in file [/var/lib/tomcat8/webapps/ROOT/WEB-INF/classes/com/dodeedo/service/UserService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userSearchRepository': Cannot resolve reference to bean 'elasticsearchTemplate' while setting bean property 'elasticsearchOperations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticsearchTemplate' defined in class path resource [com/dodeedo/config/ElasticsearchConfiguration.class]: Unsatisfied dependency expressed through method 'elasticsearchTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testClient' defined in class path resource [com/github/vanroy/springboot/autoconfigure/data/jest/ElasticsearchJestAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.searchbox.client.JestClient]: Factory method 'testClient' threw exception; nested exception is java.lang.NoSuchFieldError: LUCENE_4_0_0
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)

Did anyone face the same problem before?

**Comment by VanRoy** [comment]
Hi @ernsyn , can you check in your package ( jar or war ) , which version of elasticsearch and lucene lib is present. Or if not two version the same jars is present in your package ?

**Comment by ernsyn** [comment]
Hi @VanRoy, you're right. There were 2 versions in the war file which is puzzling. I rebuilt the war file and everything works now. 

Thanks!
