### ISSUE TITLE
AWS Example

### ISSUE THREAD

**Issue by aminmc** [VanRoy/spring-data-jest#4]
Hi there

Do you have any example configuration for Amazon ElasticSearch? How do I configure the credentials for indexing and searching in Elasticsearch via REST on Amazon?

Looks like Amazon ES is supporting version 2.3 so this library is the missing piece for me. 

Thanks

**Comment by VanRoy** [comment]
@aminmc , 

In my current AWS project, I use IP based security policy. In this case i don't have to configure AWS credentials. I just need to configure AWS ES Cluster url in  spring.data.jest.uri.

If you want to use IAM Role based security, you can add this library  on your project. https://github.com/inreachventures/aws-signing-request-interceptor

I will try it in future, and potentially include in my Jest autoconfiguration if it's work well.

Keep me in touch, i will update the documentation.

Thanks a lot.
Julien.

**Comment by aminmc** [comment]
Thanks Julien! I'll give it a go.

**Comment by aminmc** [comment]
Hi Julien

Turned out the interceptor wasn't actually being used in my previous comment. I had to do configure all the jest beans and jest elastic search bean definition myself in order to integrate with the AWS Interceptor but even now it's still failing with "The request signature we calculated does not match the signature you provided". The Access Key and Secret key are correct as I've tried it with Spring Cloud amazon APIs.

Cheers

**Comment by aminmc** [comment]
Hi Julien

Just to let you know I've managed to get it working.  I had to downgrade the aws interceptor library as there is a bug in the currently version.  I also had to create my own jest client and factory in order to get it working.  I also needed to configure the result mapper as I needed to pass in my own object mapper.

Cheers

**Comment by VanRoy** [comment]
Hi @aminmc ,

I just commit an integration with aws-signing.
Do you have few minutes, to build the snapshot and test this new feature ?

Thanks a lot.
Julien.

**Comment by aminmc** [comment]
Hi @VanRoy Will do.  I'll get back to you as soon as i can.

Cheers

**Comment by aminmc** [comment]
Hi @VanRoy I built snapshot and did the following:

```java
@Bean
        @Primary
        public ElasticsearchOperations elasticsearchTemplate(JestClient jestClient) {
            return new JestElasticsearchTemplate(jestClient, new DefaultJestResultsMapper(entityMapper));
        }
```
I need to provide my own entity mapper which has a custom object mapper.  I then updated my properties file with the following:

```
cloud.aws.credentials.accessKey=${env.AWS_ACCESS_KEY}
cloud.aws.credentials.secretKey=${env.AWS_SECRET_KEY}

spring.data.jest.uri=xxxxx
spring.data.jest.aws-region=us-east-1
```
And I'm getting:

```java
java.lang.NullPointerException: null
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:79)
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:67)
	at io.searchbox.core.SearchResult.getHits(SearchResult.java:63)
```

My pom.xml looks like:

```xml
 <dependency>
            <groupId>com.github.vanroy</groupId>
            <artifactId>spring-boot-starter-data-jest</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>
```
Do I need any other dependencies? This is my initial test. I'll look further 

Thanks

**Comment by VanRoy** [comment]
You need to add aws-signer dependency.
It's not a dependency of spring-boot-starter-data-jest at this time, because all users do not used AWS.

<dependency>
    <groupId>vc.inreach.aws</groupId>
    <artifactId>aws-signing-request-interceptor</artifactId>
    <version>0.0.14</version>
</dependency>

If your already had this dependency, please send me the full stacktrace of errors.

Thanks for your help.

**Comment by aminmc** [comment]
Hi there

I've added the following dependencies:

```xml
 <dependency>
            <groupId>com.github.vanroy</groupId>
            <artifactId>spring-boot-starter-data-jest</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>vc.inreach.aws</groupId>
            <artifactId>aws-signing-request-interceptor</artifactId>
            <version>0.0.14</version>
        </dependency>
```
And i'm getting:

```java
17610 24-08-2016 15:04:50.670 [Thread:main] INFO  o.s.core.annotation.AnnotationUtils - Failed to introspect annotations on [class com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestAWSAutoConfiguration$$EnhancerBySpringCGLIB$$311083f2]: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
```
followed by:
```java
17610 24-08-2016 15:04:55.217 [Thread:main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at io.arctech.solutions.squinky.api.SquinkyAPIServiceBootstrap.main(SquinkyAPIServiceBootstrap.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3508)
	at java.lang.Class.annotationData(Class.java:3497)
	at java.lang.Class.createAnnotationData(Class.java:3513)
	at java.lang.Class.annotationData(Class.java:3497)
	at java.lang.Class.getAnnotation(Class.java:3402)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3412)
	at org.springframework.core.annotation.AnnotatedElementUtils.hasAnnotation(AnnotatedElementUtils.java:617)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.isHandler(RequestMappingHandlerMapping.java:174)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:213)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:184)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:128)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 21 common frames omitted
```

**Comment by aminmc** [comment]
Hi @VanRoy 
Ok..i worked out what the issue was. It seems as though I was missing:
```xml
 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-aws-autoconfigure</artifactId>
            <version>1.1.0.RELEASE</version>
        </dependency>
```
and I needed cloud.aws.region.static if I'm running my app outside of AWS.
```
cloud.aws.region.static=xxx
```

Cheers!

**Comment by VanRoy** [comment]
Thanks for your help @aminmc.

The version 2.1.0 is released and I add a little sample with AWS configuration.

**Comment by aminmc** [comment]
@VanRoy Great stuff! Just updated my project to use 2.1.0.

**Comment by nithya-l** [comment]
HI,

 I am trying out a spring-data elastic with spring-boot. I would like to make the elastic version work locally and in AWS managed environment. I have installed 6.1.2 version of elastic search. The in memory one will not retain data on restart right. Is there any Git-Hub project to share for local projects.

**Comment by VanRoy** [comment]
@nithya-l,  I think you can use Spring profile to switch for local configuration to AWS configuration.

You just need to change the properties "spring.data.jest.uri" to http://localhost:9200.
