### ISSUE TITLE
[Question] How does one handle LocalDates?

### ISSUE THREAD

**Issue by mattmar10** [VanRoy/spring-data-jest#63]
How does one configure the underlying jackson objectMapper to support LocalDates  on deserialization?

I'm able to use a ElasticSearchRespository to put data in elastic search with a LocalDate type:

<img width="709" alt="screen shot 2018-05-02 at 2 28 40 pm" src="https://user-images.githubusercontent.com/4678850/39544960-519d87b4-4e15-11e8-8c40-d4a8e9ab5b01.png">

but when retrieving data, I see this error...

`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.time.LocalDate` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)`
...
A little more of the stacktrace:
```
at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1451) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1027) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1290) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[jackson-databind-2.9.5.jar:2.9.5]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992) ~[jackson-databind-2.9.5.jar:2.9.5]
        at org.springframework.data.elasticsearch.core.DefaultEntityMapper.mapToObject(DefaultEntityMapper.java:65) ~[spring-data-elasticsearch-3.0.6.RELEASE.jar:3.0.6.RELEASE]
```
...

**Comment by VanRoy** [comment]
Hi @mattmar10 ,

Do you have added 'jackson-datatype-jsr310' in your dependencies ?

If it's not work automatically you can override the EntityMapper used by spring-data-jest by declaring a JestElasticserchTemplate bean.

For sample : 




       @Bean
	public JestResultsMapper jestResultsMapper(SimpleElasticsearchMappingContext mappingContext) {

EntityMapper entityMapper = new MyEntityMapper();
return new DefaultJestResultsMapper(mappingContext, entityMapper);
	}

	@Bean
	public ElasticsearchOperations elasticsearchTemplate(JestClient client, JestResultsMapper mapper) {
		return new JestElasticsearchTemplate(client, mapper);
	}

**Comment by mattmar10** [comment]
Hi @VanRoy, 

I do have jackson-datatype-jsr310 declared as part of my compile time depenedencies. This is from my gradle build file:
`
compile "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.6"`

I'm not sure if this is the best way (just what I eventually pieced together), but I was able to get it to work by declaring a custom entity mapper:

```
public class CustomEntityMapper extends DefaultEntityMapper {

    private final ObjectMapper objectMapper;

    public CustomEntityMapper(){
        super();

        final ObjectMapper mapper = new ObjectMapper();
        JavaTimeModule javaTimeModule = new JavaTimeModule();
        javaTimeModule.addDeserializer(LocalDateTime.class, new LocalDateTimeDeserializer(DateTimeFormatter.ofPattern(DATE_FORMAT)));
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        mapper.registerModule(javaTimeModule);
        mapper.findAndRegisterModules();
        objectMapper = mapper;
    }

    @Override
    public String mapToString(Object object) throws IOException {
        return objectMapper.writeValueAsString(object);
    }

    @Override
    public <T> T mapToObject(String source, Class<T> clazz) throws IOException {
        return objectMapper.readValue(source, clazz);
    }

}
```


and then using this bean

```
    @Bean
    @Primary
    public ElasticsearchOperations elasticsearchTemplate(final JestClient jestClient,
                                                         final ElasticsearchConverter elasticsearchConverter,
                                                         final SimpleElasticsearchMappingContext simpleElasticsearchMappingContext) {
        return new JestElasticsearchTemplate(
                jestClient,
                elasticsearchConverter,
                new DefaultJestResultsMapper(simpleElasticsearchMappingContext, new CustomEntityMapper()));
    }
```

**Comment by VanRoy** [comment]
It's looks fine, It the best way that you can do with current Spring Data.

Just I think you can replace the "extends DefaultEntityMapper" by "implements EntityMapper".
You do not reuse nothing of DefaultEntityMapper, so it will be lighter that just implement EntityMapper.
