### ISSUE TITLE
All repository Error!

### ISSUE THREAD

**Issue by Delfimarime** [VanRoy/spring-data-jest#67]
The jest client creates all ES schema but when its time to create repository i get the exception:
`2018-07-16 09:35:01.387  INFO 31497 --- [  restartedMain] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@23890a88: startup date [Mon Jul 16 09:35:01 CAT 2018]; root of context hierarchy
2018-07-16 09:35:01.670  INFO 31497 --- [  restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-07-16 09:35:01.733  INFO 31497 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$830bf997] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.3.RELEASE)

2018-07-16 09:35:01.969  INFO 31497 --- [  restartedMain] mz.co.lissima.Application                : No active profile set, falling back to default profiles: default
2018-07-16 09:35:02.008  INFO 31497 --- [  restartedMain] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5f111a17: startup date [Mon Jul 16 09:35:02 CAT 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@23890a88
2018-07-16 09:35:02.870  INFO 31497 --- [  restartedMain] o.s.i.config.IntegrationRegistrar        : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2018-07-16 09:35:03.851  INFO 31497 --- [  restartedMain] o.s.cloud.context.scope.GenericScope     : BeanFactory id=2b4bfa71-3893-38b7-97f7-7bca1c750a01
2018-07-16 09:35:03.876  INFO 31497 --- [  restartedMain] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2018-07-16 09:35:03.877  INFO 31497 --- [  restartedMain] faultConfiguringBeanFactoryPostProcessor : No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
2018-07-16 09:35:03.908  INFO 31497 --- [  restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-07-16 09:35:04.010  INFO 31497 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration' of type [org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration$$EnhancerBySpringCGLIB$$2d5db4c8] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-07-16 09:35:04.094  INFO 31497 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$66f1f69a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-07-16 09:35:04.425  INFO 31497 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration$$EnhancerBySpringCGLIB$$d1e3b1c9] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-07-16 09:35:04.447  INFO 31497 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$830bf997] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-07-16 09:35:04.475  INFO 31497 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.dsl.context.IntegrationFlowContext' of type [org.springframework.integration.dsl.context.IntegrationFlowContext] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-07-16 09:35:04.947  INFO 31497 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9002 (http)
2018-07-16 09:35:04.969  INFO 31497 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-07-16 09:35:04.970  INFO 31497 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.31
2018-07-16 09:35:04.973  INFO 31497 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2018-07-16 09:35:05.066  INFO 31497 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-07-16 09:35:05.067  INFO 31497 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3059 ms
2018-07-16 09:35:05.441  WARN 31497 --- [ost-startStop-1] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2018-07-16 09:35:05.441  INFO 31497 --- [ost-startStop-1] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2018-07-16 09:35:05.450  INFO 31497 --- [ost-startStop-1] c.netflix.config.DynamicPropertyFactory  : DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@4ad4c08c
2018-07-16 09:35:06.099  INFO 31497 --- [ost-startStop-1] io.searchbox.client.AbstractJestClient   : Setting server pool to a list of 1 servers: [http://localhost:9200]
2018-07-16 09:35:06.101  INFO 31497 --- [ost-startStop-1] io.searchbox.client.JestClientFactory    : Using multi thread/connection supporting pooling connection manager
2018-07-16 09:35:06.151  INFO 31497 --- [ost-startStop-1] io.searchbox.client.JestClientFactory    : Using default GSON instance
2018-07-16 09:35:06.152  INFO 31497 --- [ost-startStop-1] io.searchbox.client.JestClientFactory    : Node Discovery disabled...
2018-07-16 09:35:06.152  INFO 31497 --- [ost-startStop-1] io.searchbox.client.JestClientFactory    : Idle connection reaping disabled...
2018-07-16 09:35:06.713  INFO 31497 --- [ost-startStop-1] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService  'taskScheduler'
2018-07-16 09:35:07.264  INFO 31497 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2018-07-16 09:35:07.269  INFO 31497 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-07-16 09:35:07.269  INFO 31497 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-07-16 09:35:07.270  INFO 31497 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-07-16 09:35:07.270  INFO 31497 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-07-16 09:35:07.270  INFO 31497 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2018-07-16 09:35:07.270  INFO 31497 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webMvcMetricsFilter' to: [/*]
2018-07-16 09:35:07.316  WARN 31497 --- [  restartedMain] o.s.b.c.c.a.DefaultBatchConfigurer       : No datasource was provided...using a Map based JobRepository
2018-07-16 09:35:07.333  INFO 31497 --- [  restartedMain] o.s.b.c.l.support.SimpleJobLauncher      : No TaskExecutor has been set, defaulting to synchronous executor.
2018-07-16 09:35:08.516  WARN 31497 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cartographyEventStoreImpl': Unsatisfied dependency expressed through field 'areas'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cartographyAreaRepository': Invocation of init method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception; nested exception is java.lang.StackOverflowError
2018-07-16 09:35:08.517  INFO 31497 --- [  restartedMain] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2018-07-16 09:35:08.524  INFO 31497 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
`
---- areas is a Repository---
`
@Repository
public interface CartographyAreaRepository
		extends ElasticsearchRepository<CartographyArea, String>, AdvancedCartographyAreaRepository {
}

The AdvancedCartographyAreaReposity 

public interface AdvancedCartographyAreaRepository {
	boolean setEnabled(@NotNull() @NotEmpty() @NotBlank() String code, @NotNull() boolean isEnabled);

	boolean setName(@NotNull() @NotEmpty() @NotBlank() String code, @NotNull() @NotEmpty() @NotBlank() String name);

	boolean setIcon(@NotNull() @NotEmpty() @NotBlank() String code, String icon);

	boolean setLastUpdated(@NotNull() @NotEmpty() @NotBlank() String code,
			@NotNull() @NotEmpty() @NotBlank() String username, @NotNull() ZonedDateTime now);
}
`

And the implementation 
`
public class CartographyAreaRepositoryImpl extends AbstractEntityRepository
		implements AdvancedCartographyAreaRepository {

	@Autowired()
	public CartographyAreaRepositoryImpl(ElasticsearchOperations operations) {
		super(operations);
	}

	@Override
	public boolean setName(@NotNull @NotEmpty @NotBlank String id, @NotNull @NotEmpty @NotBlank String name) {
		return this.update(id, update -> update.source("name", name));
	}

	@Override
	public boolean setIcon(@NotNull @NotEmpty @NotBlank String code, String icon) {
		return this.update(code, update -> update.source("icon", icon));
	}

	@Override
	public boolean setEnabled(@NotNull @NotEmpty @NotBlank String code, boolean isEnabled) {
		return this.update(code, update -> update.source("enabled", isEnabled));
	}

	@Override
	protected Class<?> getType() {
		return CartographyArea.class;
	}

}
`

The super class is just a util class

**Comment by Delfimarime** [comment]
After some struggle, i got the logs about the stackoverflow:
`Caused by: java.lang.StackOverflowError: null
	at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:140) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.core.ResolvableType.forType(ResolvableType.java:1383) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.core.ResolvableType.forField(ResolvableType.java:1086) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at com.github.vanroy.springdata.jest.MappingBuilder.getFieldType(MappingBuilder.java:322) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.isEntity(MappingBuilder.java:315) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:129) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:134) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:134) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:134) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:134) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:134) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:134) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:134) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:134) ~[spring-data-jest-3.1.2.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.MappingBuilder.mapEntity(MappingBuilder.java:134) `

**Comment by Delfimarime** [comment]
Mapping problems!
