### ISSUE TITLE
Searching multiple field not working

### ISSUE THREAD

**Issue by datavisorfrankhe** [VanRoy/spring-data-jest#72]
My entity is like this:
```
@Data
@Document(indexName="frankhe", type="books", shards = 1, replicas = 0, refreshInterval = "-1")
public class Book {
	@Id
	private String id;
	private String title;
	private String author;
	private String releaseDate;
}

```

If I am doing 
	```
List<Book> findByTitle(String title);
	List<Book> findByAuthor(String author);
```

All fine, but if I want to do search all the fields, like this:

`List<Book> findAllByTitleOrAuthor(String term);`

Now I got exceptions:

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_171]
	at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_171]
	at org.springframework.data.repository.query.Parameters.getParameter(Parameters.java:206) ~[spring-data-commons-2.0.7.RELEASE.jar:2.0.7.RELEASE]
...
```

Can I ask how to do search from multiple fields?

Thanks

**Comment by VanRoy** [comment]
Hi @datavisorfrankhe .

I guess that you need to provide two parameter if have two element in query.

Can you try this one : 

```
List<Book> findAllByTitleOrAuthor(String term, String term);
```

**Comment by datavisorfrankhe** [comment]
Thanks, that should be work.
