### ISSUE TITLE
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception; nested exception is com.github.vanroy.springdata.jest.exception.JestElasticsearchException: Cannot execute jest action , response code : 403 , error : 403 Forbidden , message : null

### ISSUE THREAD

**Issue by VigneshMurugan** [VanRoy/spring-data-jest#87]

**Comment by jeronimo13** [comment]
I've had the same issue.
Steps to reproduce: 

1. Create aws Elasticsearch service
2. Copy spring-boot-sample-data-jest-aws to you local machine
3. change config in application.properties
`spring.data.jest.uri=https://AWS_HOST_URI
cloud.aws.region.static=us-east-1`
4. Start spring boot application
5. Get this:
`Caused by: com.github.vanroy.springdata.jest.exception.JestElasticsearchException: Cannot execute jest action , response code : 403 , error : 403 Forbidden , message : null
	at com.github.vanroy.springdata.jest.mapper.DefaultErrorMapper.mapError(DefaultErrorMapper.java:30)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.execute(JestElasticsearchTemplate.java:1218)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.executeWithAcknowledge(JestElasticsearchTemplate.java:1228)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.indexExists(JestElasticsearchTemplate.java:848)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndexIfNotCreated(JestElasticsearchTemplate.java:1423)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndex(JestElasticsearchTemplate.java:177)
	at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.createIndex(AbstractElasticsearchRepository.java:96)
	at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.<init>(AbstractElasticsearchRepository.java:87)
	at org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository.<init>(SimpleElasticsearchRepository.java:36)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
	... 41 more`

**Comment by jeronimo13** [comment]
I've overcome this issue:
When setup ElasticSearch Service at AWS I choose - public access. But, when diggin into httpRequest I found aws auth header - AWSSigningRequestInterceptor took it from my credentials folder at ~/.aws (I use Mac). So, when AWS sees auth it tries to match it and when it doesn't find the match - it fails response with 403 error

I add ElasticSearch policies in IAM to my user that I have in ~/.aws/credentials and it worked out

**Comment by VanRoy** [comment]
Hi @jeronimo13 , thanks a lot for your feedback.

**Comment by MarcosEich** [comment]
> I've overcome this issue:
> When setup ElasticSearch Service at AWS I choose - public access. But, when diggin into httpRequest I found aws auth header - AWSSigningRequestInterceptor took it from my credentials folder at ~/.aws (I use Mac). So, when AWS sees auth it tries to match it and when it doesn't find the match - it fails response with 403 error
> 
> I add ElasticSearch policies in IAM to my user that I have in ~/.aws/credentials and it worked out

Thanks for this solution. I had the same issue but it is working now.
