### ISSUE TITLE
Spring Boot 2.1.0 update error

### ISSUE THREAD

**Issue by CanD42** [VanRoy/spring-data-jest#99]
Hi,

we're using Spring Boot 2.0.6 together with com.github.vanroy 3.1.5.RELEASE which works fine. Now we wanted to update to Spring Boot 2.1.0 but got the following error in out test cases. Can this please be fixed? 
```
Caused by: java.lang.NoSuchMethodError: org.springframework.data.elasticsearch.core.DefaultEntityMapper: method <init>()V not found
	at com.github.vanroy.springdata.jest.mapper.DefaultJestResultsMapper.<init>(DefaultJestResultsMapper.java:55) ~[spring-data-jest-3.1.5.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.<init>(JestElasticsearchTemplate.java:123) ~[spring-data-jest-3.1.5.RELEASE.jar:na]
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.<init>(JestElasticsearchTemplate.java:101) ~[spring-data-jest-3.1.5.RELEASE.jar:na]
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestDataAutoConfiguration.elasticsearchTemplate(ElasticsearchJestDataAutoConfiguration.java:25) ~[spring-boot-starter-data-jest-3.1.5.RELEASE.jar:na]
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestDataAutoConfiguration$$EnhancerBySpringCGLIB$$3f8713b7.CGLIB$elasticsearchTemplate$0(<generated>) ~[spring-boot-starter-data-jest-3.1.5.RELEASE.jar:na]
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestDataAutoConfiguration$$EnhancerBySpringCGLIB$$3f8713b7$$FastClassBySpringCGLIB$$2144c3c1.invoke(<generated>) ~[spring-boot-starter-data-jest-3.1.5.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestDataAutoConfiguration$$EnhancerBySpringCGLIB$$3f8713b7.elasticsearchTemplate(<generated>) ~[spring-boot-starter-data-jest-3.1.5.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	... 52 common frames omitted
```
Thanks,
Daniel

**Comment by VanRoy** [comment]
Hi @CanD42. The new version if 3.2.0.RELEASE released tonight is now compatible with SpringBoot 2.1.0.
Please feel free to feedback if you detect some issues.
Thanks.

**Comment by CanD42** [comment]
Hi @VanRoy,
thanks for the quick update. I tried the new version and the startup problem seems to be solved. However, some of our queries are failing because ES6 is now required and we're running still on ES5. So next task on our side would be a ES6 migration
Thanks,
Daniel
